In [1]:
#initializing dependencies
import numpy as np
import pandas as pd
import tensorflow as tf

In [11]:
data=pd.read_csv('Dataset\\survey.csv')
data.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [12]:
data=data.drop(["Timestamp","comments"],axis=1)
data.head()

,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,United States,IL,NaN,No,Yes,Often,6-25,No,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,TX,NaN,No,No,Never,100-500,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [22]:
data.shape

(1259, 25)

In [29]:
data.isnull().sum()

Age                            0
Gender                         0
Country                        0
state                        515
self_employed                 18
family_history                 0
treatment                      0
work_interfere               264
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
dtype: int64

In [42]:
unique_val=[]
for i in data.columns:
    temp={i:data[i].unique()}
    unique_val.append(temp)

In [53]:
unique_val

[{'Age': array([         37,          44,          32,          31,          33,
                  35,          39,          42,          23,          29,
                  36,          27,          46,          41,          34,
                  30,          40,          38,          50,          24,
                  18,          28,          26,          22,          19,
                  25,          45,          21,         -29,          43,
                  56,          60,          54,         329,          55,
         99999999999,          48,          20,          57,          58,
                  47,          62,          51,          65,          49,
               -1726,           5,          53,          61,           8,
                  11,          -1,          72], dtype=int64)},
 {'Gender': array(['Female', 'M', 'Male', 'male', 'female', 'm', 'Male-ish', 'maile',
         'Trans-female', 'Cis Female', 'F', 'something kinda male?',
         'Cis Male', 'Woman', 'f', 'Mal', 'Male (CIS)', 'queer/she/they',
         'non-binary', 'Femake', 'woman', 'Make', 'Nah', 'All', 'Enby',
         'fluid', 'Genderqueer', 'Female ', 'Androgyne', 'Agender',
         'cis-female/femme', 'Guy (-ish) ^_^', 'male leaning androgynous',
         'Male ', 'Man', 'Trans woman', 'msle', 'Neuter', 'Female (trans)',
         'queer', 'Female (cis)', 'Mail', 'cis male', 'A little about you',
         'Malr', 'p', 'femail', 'Cis Man',
         'ostensibly male, unsure what that really means'], dtype=object)},
 {'Country': array(['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France',
         'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia',
         'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica',
         'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden',
         'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand',
         'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel',
         'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan',
         'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark',
         'Bahamas, The', 'Greece', 'Moldova', 'Georgia', 'China',
         'Czech Republic', 'Philippines'], dtype=object)},
 {'state': array(['IL', 'IN', nan, 'TX', 'TN', 'MI', 'OH', 'CA', 'CT', 'MD', 'NY',
         'NC', 'MA', 'IA', 'PA', 'WA', 'WI', 'UT', 'NM', 'OR', 'FL', 'MN',
         'MO', 'AZ', 'CO', 'GA', 'DC', 'NE', 'WV', 'OK', 'KS', 'VA', 'NH',
         'KY', 'AL', 'NV', 'NJ', 'SC', 'VT', 'SD', 'ID', 'MS', 'RI', 'WY',
         'LA', 'ME'], dtype=object)},
 {'self_employed': array([nan, 'Yes', 'No'], dtype=object)},
 {'family_history': array(['No', 'Yes'], dtype=object)},
 {'treatment': array(['Yes', 'No'], dtype=object)},
 {'work_interfere': array(['Often', 'Rarely', 'Never', 'Sometimes', nan], dtype=object)},
 {'no_employees': array(['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000'],
        dtype=object)},
 {'remote_work': array(['No', 'Yes'], dtype=object)},
 {'tech_company': array(['Yes', 'No'], dtype=object)},
 {'benefits': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'care_options': array(['Not sure', 'No', 'Yes'], dtype=object)},
 {'wellness_program': array(['No', "Don't know", 'Yes'], dtype=object)},
 {'seek_help': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'anonymity': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'leave': array(['Somewhat easy', "Don't know", 'Somewhat difficult',
         'Very difficult', 'Very easy'], dtype=object)},
 {'mental_health_consequence': array(['No', 'Maybe', 'Yes'], dtype=object)},
 {'phys_health_consequence': array(['No', 'Yes', 'Maybe'], dtype=object)},
 {'coworkers': array(['Some of them', 'No', 'Yes'], dtype=object)},
 {'supervisor': array(['Yes', 'No', 'Some of them'], dtype=object)},
 {'mental_health_interview': array(['No', 'Yes', 'Maybe'], dtype=object)},
 {'phys_health_interview': array(['Maybe', 'No', 'Yes'], dtype=object)},
 {'mental_vs_physical': array(['Yes', "Don't know", 'No'], dtype=object)},
 {'obs_consequence': array(['No', 'Yes'], dtype=object)}]

In [65]:
def gender(g):
    g_=""
    g=g.lower()
    for i in range(len(g)):
        if g[i]=='-' or g[i]=='/' or g[i]=='?':
            g_+=" "
        else:
            g_+=g[i]
    l=list(g_.split(" "))
    k=0
    for i in l:
        if(i=="female" or i=="f" or i=="femake" or i=="woman" or i=="she" or i=="femail" or i=="queer" or i=="Androgyne" or i=="Agender"):
            k=1
            break
    return k

# 0-male 1-female

In [67]:
g="female"
print(gender(g))

1

In [60]:
for i in range(len(g)):
        if g[i]=='-' or g[i]=='/':
            print(g[i])

-